/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as R404IndexRouteImport } from './routes/404/index'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthToolsIndexRouteImport } from './routes/_auth/tools/index'
import { Route as AuthModelsIndexRouteImport } from './routes/_auth/models/index'
import { Route as AuthInboxesIndexRouteImport } from './routes/_auth/inboxes/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthAgentsIndexRouteImport } from './routes/_auth/agents/index'
import { Route as Auth403IndexRouteImport } from './routes/_auth/403/index'
import { Route as AuthModelsConfigRouteImport } from './routes/_auth/models/config'
import { Route as AuthModelsProviderIdRouteImport } from './routes/_auth/models/$providerId'
import { Route as AuthInboxesNewRouteImport } from './routes/_auth/inboxes/new'
import { Route as AuthAgentsNewRouteImport } from './routes/_auth/agents/new'
import { Route as AuthAgentsAgentIdRouteImport } from './routes/_auth/agents/$agentId'
import { Route as AuthSettingsInboxesIndexRouteImport } from './routes/_auth/settings/inboxes/index'
import { Route as AuthInboxesInboxIdSettingsRouteImport } from './routes/_auth/inboxes/$inboxId.settings'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404IndexRoute = R404IndexRouteImport.update({
  id: '/404/',
  path: '/404/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthToolsIndexRoute = AuthToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModelsIndexRoute = AuthModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInboxesIndexRoute = AuthInboxesIndexRouteImport.update({
  id: '/inboxes/',
  path: '/inboxes/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsIndexRoute = AuthAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AuthRoute,
} as any)
const Auth403IndexRoute = Auth403IndexRouteImport.update({
  id: '/403/',
  path: '/403/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModelsConfigRoute = AuthModelsConfigRouteImport.update({
  id: '/models/config',
  path: '/models/config',
  getParentRoute: () => AuthRoute,
} as any)
const AuthModelsProviderIdRoute = AuthModelsProviderIdRouteImport.update({
  id: '/models/$providerId',
  path: '/models/$providerId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInboxesNewRoute = AuthInboxesNewRouteImport.update({
  id: '/inboxes/new',
  path: '/inboxes/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsNewRoute = AuthAgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsAgentIdRoute = AuthAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsInboxesIndexRoute =
  AuthSettingsInboxesIndexRouteImport.update({
    id: '/settings/inboxes/',
    path: '/settings/inboxes/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthInboxesInboxIdSettingsRoute =
  AuthInboxesInboxIdSettingsRouteImport.update({
    id: '/inboxes/$inboxId/settings',
    path: '/inboxes/$inboxId/settings',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/inboxes/new': typeof AuthInboxesNewRoute
  '/models/$providerId': typeof AuthModelsProviderIdRoute
  '/models/config': typeof AuthModelsConfigRoute
  '/403/': typeof Auth403IndexRoute
  '/agents/': typeof AuthAgentsIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/inboxes/': typeof AuthInboxesIndexRoute
  '/models/': typeof AuthModelsIndexRoute
  '/tools/': typeof AuthToolsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/inboxes/$inboxId/settings': typeof AuthInboxesInboxIdSettingsRoute
  '/settings/inboxes/': typeof AuthSettingsInboxesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404IndexRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/agents/new': typeof AuthAgentsNewRoute
  '/inboxes/new': typeof AuthInboxesNewRoute
  '/models/$providerId': typeof AuthModelsProviderIdRoute
  '/models/config': typeof AuthModelsConfigRoute
  '/403': typeof Auth403IndexRoute
  '/agents': typeof AuthAgentsIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/inboxes': typeof AuthInboxesIndexRoute
  '/models': typeof AuthModelsIndexRoute
  '/tools': typeof AuthToolsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/inboxes/$inboxId/settings': typeof AuthInboxesInboxIdSettingsRoute
  '/settings/inboxes': typeof AuthSettingsInboxesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/404/': typeof R404IndexRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/_auth/agents/$agentId': typeof AuthAgentsAgentIdRoute
  '/_auth/agents/new': typeof AuthAgentsNewRoute
  '/_auth/inboxes/new': typeof AuthInboxesNewRoute
  '/_auth/models/$providerId': typeof AuthModelsProviderIdRoute
  '/_auth/models/config': typeof AuthModelsConfigRoute
  '/_auth/403/': typeof Auth403IndexRoute
  '/_auth/agents/': typeof AuthAgentsIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/inboxes/': typeof AuthInboxesIndexRoute
  '/_auth/models/': typeof AuthModelsIndexRoute
  '/_auth/tools/': typeof AuthToolsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/inboxes/$inboxId/settings': typeof AuthInboxesInboxIdSettingsRoute
  '/_auth/settings/inboxes/': typeof AuthSettingsInboxesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404/'
    | '/login/'
    | '/register/'
    | '/agents/$agentId'
    | '/agents/new'
    | '/inboxes/new'
    | '/models/$providerId'
    | '/models/config'
    | '/403/'
    | '/agents/'
    | '/dashboard/'
    | '/inboxes/'
    | '/models/'
    | '/tools/'
    | '/users/'
    | '/inboxes/$inboxId/settings'
    | '/settings/inboxes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/login'
    | '/register'
    | '/agents/$agentId'
    | '/agents/new'
    | '/inboxes/new'
    | '/models/$providerId'
    | '/models/config'
    | '/403'
    | '/agents'
    | '/dashboard'
    | '/inboxes'
    | '/models'
    | '/tools'
    | '/users'
    | '/inboxes/$inboxId/settings'
    | '/settings/inboxes'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/404/'
    | '/login/'
    | '/register/'
    | '/_auth/agents/$agentId'
    | '/_auth/agents/new'
    | '/_auth/inboxes/new'
    | '/_auth/models/$providerId'
    | '/_auth/models/config'
    | '/_auth/403/'
    | '/_auth/agents/'
    | '/_auth/dashboard/'
    | '/_auth/inboxes/'
    | '/_auth/models/'
    | '/_auth/tools/'
    | '/_auth/users/'
    | '/_auth/inboxes/$inboxId/settings'
    | '/_auth/settings/inboxes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  R404IndexRoute: typeof R404IndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404/': {
      id: '/404/'
      path: '/404'
      fullPath: '/404/'
      preLoaderRoute: typeof R404IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tools/': {
      id: '/_auth/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthToolsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/models/': {
      id: '/_auth/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthModelsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inboxes/': {
      id: '/_auth/inboxes/'
      path: '/inboxes'
      fullPath: '/inboxes/'
      preLoaderRoute: typeof AuthInboxesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/': {
      id: '/_auth/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AuthAgentsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/403/': {
      id: '/_auth/403/'
      path: '/403'
      fullPath: '/403/'
      preLoaderRoute: typeof Auth403IndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/models/config': {
      id: '/_auth/models/config'
      path: '/models/config'
      fullPath: '/models/config'
      preLoaderRoute: typeof AuthModelsConfigRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/models/$providerId': {
      id: '/_auth/models/$providerId'
      path: '/models/$providerId'
      fullPath: '/models/$providerId'
      preLoaderRoute: typeof AuthModelsProviderIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inboxes/new': {
      id: '/_auth/inboxes/new'
      path: '/inboxes/new'
      fullPath: '/inboxes/new'
      preLoaderRoute: typeof AuthInboxesNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/new': {
      id: '/_auth/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AuthAgentsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents/$agentId': {
      id: '/_auth/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthAgentsAgentIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/inboxes/': {
      id: '/_auth/settings/inboxes/'
      path: '/settings/inboxes'
      fullPath: '/settings/inboxes/'
      preLoaderRoute: typeof AuthSettingsInboxesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inboxes/$inboxId/settings': {
      id: '/_auth/inboxes/$inboxId/settings'
      path: '/inboxes/$inboxId/settings'
      fullPath: '/inboxes/$inboxId/settings'
      preLoaderRoute: typeof AuthInboxesInboxIdSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAgentsAgentIdRoute: typeof AuthAgentsAgentIdRoute
  AuthAgentsNewRoute: typeof AuthAgentsNewRoute
  AuthInboxesNewRoute: typeof AuthInboxesNewRoute
  AuthModelsProviderIdRoute: typeof AuthModelsProviderIdRoute
  AuthModelsConfigRoute: typeof AuthModelsConfigRoute
  Auth403IndexRoute: typeof Auth403IndexRoute
  AuthAgentsIndexRoute: typeof AuthAgentsIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthInboxesIndexRoute: typeof AuthInboxesIndexRoute
  AuthModelsIndexRoute: typeof AuthModelsIndexRoute
  AuthToolsIndexRoute: typeof AuthToolsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthInboxesInboxIdSettingsRoute: typeof AuthInboxesInboxIdSettingsRoute
  AuthSettingsInboxesIndexRoute: typeof AuthSettingsInboxesIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsAgentIdRoute: AuthAgentsAgentIdRoute,
  AuthAgentsNewRoute: AuthAgentsNewRoute,
  AuthInboxesNewRoute: AuthInboxesNewRoute,
  AuthModelsProviderIdRoute: AuthModelsProviderIdRoute,
  AuthModelsConfigRoute: AuthModelsConfigRoute,
  Auth403IndexRoute: Auth403IndexRoute,
  AuthAgentsIndexRoute: AuthAgentsIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthInboxesIndexRoute: AuthInboxesIndexRoute,
  AuthModelsIndexRoute: AuthModelsIndexRoute,
  AuthToolsIndexRoute: AuthToolsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthInboxesInboxIdSettingsRoute: AuthInboxesInboxIdSettingsRoute,
  AuthSettingsInboxesIndexRoute: AuthSettingsInboxesIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  R404IndexRoute: R404IndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
