-- 客服业务域与 Agent 域统一 PostgreSQL，并补齐 AppKey 隔离和 Inbox-Agent 绑定。

ALTER TABLE agents ADD COLUMN IF NOT EXISTS app_key VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE bots ADD COLUMN IF NOT EXISTS app_key VARCHAR(64) NOT NULL DEFAULT '';
DROP INDEX IF EXISTS idx_bots_user_unique;
CREATE UNIQUE INDEX IF NOT EXISTS uq_bots_app_user ON bots (app_key, bot_user_id);
CREATE INDEX IF NOT EXISTS idx_agents_app_owner_status ON agents (app_key, owner_id, status);
CREATE INDEX IF NOT EXISTS idx_bots_app_owner_status ON bots (app_key, owner_id, status);
CREATE UNIQUE INDEX IF NOT EXISTS uq_agents_app_id ON agents (app_key, id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bots_app_id ON bots (app_key, id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_bab_agent_active ON bot_agent_bindings (agent_id) WHERE status = 'active';

CREATE TABLE IF NOT EXISTS apps (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_key VARCHAR(64) NOT NULL,
	app_secret VARCHAR(255) NOT NULL DEFAULT '',
	app_status SMALLINT NOT NULL DEFAULT 0,
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_name VARCHAR(100) NOT NULL DEFAULT '',
	CONSTRAINT uq_apps_app_key UNIQUE (app_key)
);

CREATE TABLE IF NOT EXISTS appexts (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	app_key VARCHAR(64) NOT NULL,
	app_item_key VARCHAR(50) NOT NULL,
	app_item_value VARCHAR(2048) NOT NULL DEFAULT '',
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT uq_appexts_app_item UNIQUE (app_key, app_item_key)
);

CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id VARCHAR(64) NOT NULL,
	nickname VARCHAR(50) NOT NULL DEFAULT '',
	avator VARCHAR(200) NOT NULL DEFAULT '',
	login_account VARCHAR(64) NOT NULL DEFAULT '',
	email VARCHAR(128) NOT NULL DEFAULT '',
	login_pass VARCHAR(128) NOT NULL DEFAULT '',
	role SMALLINT NOT NULL DEFAULT 1,
	status INTEGER NOT NULL DEFAULT 1,
	im_token VARCHAR(512) NOT NULL DEFAULT '',
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_users_app_account UNIQUE (app_key, login_account),
	CONSTRAINT uq_users_app_user UNIQUE (app_key, user_id)
);
CREATE INDEX IF NOT EXISTS idx_users_app_key ON users (app_key);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_app_email_nonempty ON users (app_key, email) WHERE email <> '';

CREATE TABLE IF NOT EXISTS customers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_id VARCHAR(64) NOT NULL,
	nickname VARCHAR(50) NOT NULL DEFAULT '',
	avator VARCHAR(200) NOT NULL DEFAULT '',
	phone VARCHAR(50) NOT NULL DEFAULT '',
	email VARCHAR(128) NOT NULL DEFAULT '',
	identifier VARCHAR(255) NOT NULL DEFAULT '',
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_customers_app_customer UNIQUE (app_key, customer_id)
);
CREATE INDEX IF NOT EXISTS idx_customers_app_identifier ON customers (app_key, identifier);

CREATE TABLE IF NOT EXISTS inboxes (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inbox_id VARCHAR(64) NOT NULL,
	channel_type VARCHAR(50) NOT NULL,
	channel_conf TEXT NOT NULL DEFAULT '',
	name VARCHAR(50) NOT NULL DEFAULT '',
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_inboxes_app_inbox UNIQUE (app_key, inbox_id)
);

CREATE TABLE IF NOT EXISTS customerinboxrels (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	customer_id VARCHAR(64) NOT NULL,
	inbox_id VARCHAR(64) NOT NULL,
	source_id VARCHAR(64) NOT NULL,
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_customerinboxrels_source UNIQUE (app_key, source_id),
	CONSTRAINT uq_customerinboxrels_customer_inbox UNIQUE (app_key, customer_id, inbox_id)
);
CREATE INDEX IF NOT EXISTS idx_customerinboxrels_inbox ON customerinboxrels (app_key, inbox_id);

CREATE TABLE IF NOT EXISTS inboxmembers (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	inbox_id VARCHAR(64) NOT NULL,
	member_id VARCHAR(64) NOT NULL,
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_inboxmembers_app_member UNIQUE (app_key, inbox_id, member_id)
);

CREATE TABLE IF NOT EXISTS tickets (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	ticket_id VARCHAR(64) NOT NULL,
	source_id VARCHAR(64) NOT NULL DEFAULT '',
	assignee_id VARCHAR(64) NOT NULL DEFAULT '',
	customer_id VARCHAR(64) NOT NULL DEFAULT '',
	inbox_id VARCHAR(64) NOT NULL DEFAULT '',
	channel_type VARCHAR(50) NOT NULL DEFAULT '',
	status SMALLINT NOT NULL DEFAULT 0,
	created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_time TIMESTAMPTZ NOT NULL DEFAULT now(),
	app_key VARCHAR(64) NOT NULL,
	CONSTRAINT uq_tickets_app_ticket UNIQUE (app_key, ticket_id)
);
CREATE INDEX IF NOT EXISTS idx_tickets_app_source ON tickets (app_key, source_id);
CREATE INDEX IF NOT EXISTS idx_tickets_app_inbox_status ON tickets (app_key, inbox_id, status);

CREATE TABLE IF NOT EXISTS inbox_agent_bindings (
	id VARCHAR(64) PRIMARY KEY,
	app_key VARCHAR(64) NOT NULL,
	inbox_id VARCHAR(64) NOT NULL,
	agent_id VARCHAR(64) NOT NULL,
	bot_id VARCHAR(64) NOT NULL,
	status VARCHAR(16) NOT NULL DEFAULT 'active',
	sync_error TEXT,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	CONSTRAINT ck_inbox_agent_bindings_status CHECK (status IN ('active', 'inactive')),
	CONSTRAINT uq_inbox_agent_bindings_inbox UNIQUE (app_key, inbox_id),
	FOREIGN KEY(app_key, inbox_id) REFERENCES inboxes (app_key, inbox_id) ON DELETE CASCADE,
	FOREIGN KEY(app_key, agent_id) REFERENCES agents (app_key, id) ON DELETE RESTRICT,
	FOREIGN KEY(app_key, bot_id) REFERENCES bots (app_key, id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_iab_agent_status ON inbox_agent_bindings (app_key, agent_id, status);

CREATE TABLE IF NOT EXISTS agent_first_recharge_grants (
	app_key VARCHAR(64) NOT NULL,
	owner_id VARCHAR(64) NOT NULL,
	agent_id VARCHAR(64) NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	granted_at TIMESTAMPTZ,
	PRIMARY KEY (app_key, owner_id),
	FOREIGN KEY(app_key, agent_id) REFERENCES agents (app_key, id) ON DELETE CASCADE
);
