-- 工单自动关闭 + 评价系统（PostgreSQL 版本）。
-- TIPS: 与 commons/dbcommons/sqls/20260730.sql 同步字段语义。

ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS last_user_msg_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS closed_at        TIMESTAMPTZ NULL;

CREATE INDEX IF NOT EXISTS idx_tickets_app_luma ON tickets (app_key, last_user_msg_at);

CREATE TABLE IF NOT EXISTS ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_key VARCHAR(20) NOT NULL DEFAULT '',
  ticket_id VARCHAR(50) NOT NULL DEFAULT '',
  sender_id VARCHAR(64) NOT NULL DEFAULT '',
  sender_role VARCHAR(16) NOT NULL DEFAULT '',
  msg_id VARCHAR(64) NOT NULL DEFAULT '',
  msg_type VARCHAR(16) NOT NULL DEFAULT 'jg:text',
  created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uk_ticket_messages_app_msg UNIQUE (app_key, msg_id)
);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_app_ticket_time ON ticket_messages (app_key, ticket_id, created_time);

CREATE TABLE IF NOT EXISTS ticket_ratings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_key VARCHAR(20) NOT NULL DEFAULT '',
  ticket_id VARCHAR(50) NOT NULL DEFAULT '',
  customer_id VARCHAR(64) NOT NULL DEFAULT '',
  assignee_id VARCHAR(64) NOT NULL DEFAULT '',
  rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  source VARCHAR(16) NOT NULL DEFAULT 'card_button',
  created_time TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uk_ticket_ratings_app_ticket_customer UNIQUE (app_key, ticket_id, customer_id)
);
CREATE INDEX IF NOT EXISTS idx_ticket_ratings_app_assignee_time ON ticket_ratings (app_key, assignee_id, created_time);
