-- 工单是否转人工：持久化事实 + 事件流水（PostgreSQL 版本）。
-- TIPS: 与 commons/dbcommons/sqls/20260729.sql 同步字段语义；本迁移只追加列与新建表，不做字段重命名。

ALTER TABLE tickets
  ADD COLUMN IF NOT EXISTS is_human_taken_over BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS human_taken_over_at TIMESTAMPTZ NULL,
  ADD COLUMN IF NOT EXISTS human_taken_over_by VARCHAR(64) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_tickets_app_human ON tickets (app_key, is_human_taken_over);

CREATE TABLE IF NOT EXISTS ticket_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  app_key VARCHAR(64) NOT NULL DEFAULT '',
  ticket_id VARCHAR(64) NOT NULL DEFAULT '',
  event_type VARCHAR(32) NOT NULL DEFAULT '',
  operator_id VARCHAR(64) NOT NULL DEFAULT '',
  operator_type VARCHAR(16) NOT NULL DEFAULT '',
  payload JSONB NULL,
  created_time TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_ticket_events_app_ticket_type ON ticket_events (app_key, ticket_id, event_type);
CREATE INDEX IF NOT EXISTS idx_ticket_events_app_type_time ON ticket_events (app_key, event_type, created_time);
